print("Are you ready?")
print("Are you ready?")
print("Adrenaline is pumping")
print("Adrenaline is pumping")
print("Generator, automatic lover")
print("Atomic, atomic, overdrive")
print("Blockbuster, brain power")
print("Call me a leader, cocaine")
print("Innovator, killer machine")
print("There's no fate, take control")
print("Brain power")
print("Let the bass kick")
print("O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A- JO-ooo-oo-oo-oo EEEEO-A-AAA-AAAA")
print("O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A-JO-ooo-oo-oo-oo EEEEO-A-AAA-AAAA")
print("O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A-JO-ooo-oo-oo-oo EEEEO-A-AAA-AAAA-O----------")